Deployment:
  tasks:
    – export DEPLOYPATH=/home/yoctan/public_html/poker/cp-panel
    – /bin/cp -R .vscode $DEPLOYPATH
    – /bin/cp -R assets $DEPLOYPATH
    – /bin/cp -R css $DEPLOYPATH
    – /bin/cp -R fonts $DEPLOYPATH
    – /bin/cp -R img $DEPLOYPATH
    – /bin/cp -R js $DEPLOYPATH
    /bin/cp index.html $DEPLOYPATH