##### THIS ALLOWS US TO DEPLOY THE SITE FROM A GIT REPO ######
---
deployment:
  tasks:
    - export DEPLOYPATH=/home/yoctan/public_html/Poker
    - /bin/cp -f * $DEPLOYPATH
    - /bin/cp -R * $DEPLOYPATH